#8 added hamming distance calculation and tests for it
fornit1917/imagebase pull request #11
Opened 2020-11-03 18:22 UTC by MShemur

2020-11-04 12:08 UTC, fornit1917 requested changes

2020-11-04 12:08 UTC, fornit1917 commented on ImageBase.Common.UnitTests/HammingDistanceUnitTests.cs
> +        public static IEnumerable<object[]> Strings =>
можно (нужно) string[] вместо object[] везде писать

2020-11-04 12:08 UTC, fornit1917 commented on ImageBase.Common.UnitTests/HammingDistanceUnitTests.cs
> +        public void CalculateString(string a, string b, int expected)
Calculate**s**ForStrings

2020-11-04 12:08 UTC, fornit1917 commented on ImageBase.Common.UnitTests/HammingDistanceUnitTests.cs
> +        public void CalculateLong(long a, long b, int expected)
Calculate**s**ForStrings

2020-11-04 12:08 UTC, fornit1917 commented on ImageBase.Common.UnitTests/HammingDistanceUnitTests.cs
> +        public void CalculateBitArray(BitArray a, BitArray b, int expected)
Calculate**s**ForBitArrays

2020-11-04 12:08 UTC, fornit1917 commented on ImageBase.Common.UnitTests/HammingDistanceUnitTests.cs
> +        public static IEnumerable<object[]> Bits =>
стоит перенести выше, там где Strings.

Структура обычно такая: сначала тестовые данные, потом тестовые методы. Ну и аналогично object[] тут писать не очень хорошо, лучше конкретный тип

2020-11-04 12:08 UTC, fornit1917 commented on ImageBase.Common/HammingDistance.cs
> +            var splitFirst = a.ToCharArray();
создание лишних объектов в куче. Мы можем перебирать символы непосредственно у самой строки.

var лучше не писать тогда, когда справа не очевиден тип.

Т.е.

```
var s = "some tring"; // хорошо
var obj = new SomeClassName(); // хорошо
var obj = SomeMethodCall(); // плохо, при чтении кода непонятно что за тип

TypeName obj = SomeMethodCall(); // хорошо
```

2020-11-04 12:08 UTC, fornit1917 commented on ImageBase.Common/HammingDistance.cs
> +            return Calculate(new BitArray(BitConverter.GetBytes(a)), new BitArray(BitConverter.GetBytes(b)));
интересная задача - сделать это без необходимости создавать в куче лишние BitArray и byte[], а попробовать всё сделать на битовых сдвигах и прочих битовых операциях непосредственно с long-ами. Попробуешь?

Т.е. берёшь число a ^ b и считаешь, сколько битов в нём оказались равны 1.

2020-11-04 18:28 UTC, MShemur commented on ImageBase.Common.UnitTests/HammingDistanceUnitTests.cs
> +        public static IEnumerable<object[]> Strings =>
xUnit не дает - хочет objects. да и у нас во входящих данные не только строки - первые (входящие 2) это строки, а последний (expected) это int

2020-11-05 05:35 UTC, fornit1917 requested changes

2020-11-05 05:35 UTC, fornit1917 commented on ImageBase.Common.UnitTests/HammingDistanceUnitTests.cs
> +        public void CalculateForStrings(string a, string b, int expected)
Мелкое замечание  - Не calculate, а calculate**S**. По английской грамматике. "Считает для строк", 3-е лицо.

2020-11-09 15:41 UTC, merged