# 14 Add models, migration, services
fornit1917/imagebase pull request #16
Opened 2020-11-10 14:21 UTC by Olya73

Ok. I've tried to make Services for working with a context. 

I found that the generated db contained one more entity (AspNetUsers) which had the same attributes as the "users" table had. So, I fixed it in the context and deleted the migration) and made the new one with an Identity, image, catalog etc.
I did some changes in the project tree.

I hope, you will suggest the better way to organize classes and how to deal with many-to-many.

2020-11-10 15:47 UTC, fornit1917 requested changes

2020-11-10 15:47 UTC, fornit1917 commented on ImageBase.WebApp/Controllers/HomeController.cs
> +                roles = (List<string>)await _userManager.GetRolesAsync(user);
добавились лишние пробелы в конце строки, ненужное изменение

2020-11-10 15:47 UTC, fornit1917 commented on ImageBase.WebApp/Data/ConfigurationDataBase/ConfigurationPostgreSQL/CatalogConfiguration.cs
> +            entityBuilder.Property(c => c.Name).HasColumnName("name").HasMaxLength(15).IsRequired();
15 маловато будет) символов 50 давай

2020-11-10 15:47 UTC, fornit1917 commented on ImageBase.WebApp/Data/ConfigurationDataBase/ConfigurationPostgreSQL/CatalogConfiguration.cs
> +            entityBuilder.Property(c => c.UserId).HasColumnName("user_id").IsRequired();
почему IsRequired? У общих папок null же будет

2020-11-10 15:47 UTC, fornit1917 commented on ImageBase.WebApp/Data/ConfigurationDataBase/ConfigurationPostgreSQL/ImageCatalogConfiguration.cs
> +            entityBuilder.HasKey(ikw => ikw.Id);
Колонку Id можно попробовать отсюда убрать, оставить только ImageId и CatalogId, и сделать на них составной первичный ключ

2020-11-10 15:47 UTC, fornit1917 commented on ImageBase.WebApp/Data/ConfigurationDataBase/ConfigurationPostgreSQL/ImageKeyWordConfiguration.cs
> +        public ImageKeyWordConfiguration(EntityTypeBuilder<ImageKeyWord> entityBuilder)
ой, я имел в виду их просто текстовым полем сделать внутри image, как description.

2020-11-10 15:47 UTC, fornit1917 commented on ImageBase.WebApp/Data/Dtos/AddImageDto.cs
> +        public List<long> CatalogsId { get; set; }
Списки во множественном числе лучше называть, Id**s**

2020-11-10 15:47 UTC, fornit1917 commented on ImageBase.WebApp/Data/Models/BaseEntity.cs
> +    public class BaseEntity
Лучше дженерик классом сделать, чтоб вместо long другой тип можно было писать (почти везде int предпочтительнее).
А вообще можно и не использовать такой базовый класс.

2020-11-10 15:47 UTC, fornit1917 commented on ImageBase.WebApp/Data/Models/Catalog.cs
> +        public Catalog ParentCatalog { get; set; }
для читаемости будет лучше писать сначала свойства-колонки, а свойства со связанными сущностями отдельно ниже

2020-11-10 15:47 UTC, fornit1917 commented on ImageBase.WebApp/Repository/Storage/ImageCatalogRepository.cs
> +    public class ImageCatalogRepository : Repository<ImageCatalog>, IImageCatalogRepository
это репозиторий для таблицы связей? можно в общем-то обойтись и без него

2020-11-10 15:47 UTC, fornit1917 commented on ImageBase.WebApp/Service/Implementation/CatalogService.cs
> +        public void CreateCatalog(CatalogDto catalogDto)
всё надо на асинхронные методы переделать, SaveChangesAsync

2020-11-10 15:47 UTC, fornit1917 commented on ImageBase.WebApp/Repository/Storage/ImageRepository.cs
> +namespace ImageBase.WebApp.Repository.Storage
ты папку назвала Repository, хотя другие называются во множественном числе (Controllers, Migrations, Views, ....)
Нужно поддерживать единообразие. Поэтому Repositories, Services.

Не вижу смысла еще одну вложенную папку Storage иметь.

2020-11-10 15:47 UTC, fornit1917 commented on ImageBase.WebApp/Service/Implementation/ImageCatalogService.cs
> +        public IEnumerable<ImageDto> GetImagesByIdCatalog(long id)
Порядок слов немного странный. GetImagesByCatalog или GetImagesByCatalogId будет лучше.

2020-11-10 15:47 UTC, fornit1917 commented on ImageBase.WebApp/Repository/Storage/ImageCatalogRepository.cs
> +        public IEnumerable<ImageCatalog> GetCatalogWithImages(long id)
а если там миллиард картинок в папке?

Лучше список картинок по каталогу получать в отдельном методе, возвращающем Image[], и принимающем параметры limit и offset, чтоб постраничную загрузку списка картинок можно было делать.

2020-11-10 15:47 UTC, fornit1917 commented on ImageBase.WebApp/Startup.cs
> +            services.AddTransient<IImageService, ImageService>();
тоже можно AddScoped

2020-11-10 15:47 UTC, fornit1917 commented on ImageBase.WebApp/appsettings.json
> +    "AspPostgreSQLContext": "Host=localhost;Port=5432;Database=picture_db1;Integrated Security=true;Username=postgres;Password=1234;"
это изменение тут точно должно быть?

2020-11-10 15:47 UTC, fornit1917 commented on ImageBase.WebApp/Repository/Storage/ImageCatalogRepository.cs
> +        public ImageCatalog GetImageCatalogByIdFK(long idImg, long idCat)
работу с бд асинхронную надо делать.

2020-11-10 15:47 UTC, fornit1917 commented on ImageBase.WebApp/Data/Dtos/CatalogDto.cs
> +    public class CatalogDto
почему бы сюда Id не добавить? Ты же эту dto-шку будешь на фронтенд передавать, а на фронтенде айдишники нужны

2020-11-10 21:01 UTC, Olya73 commented on ImageBase.WebApp/Data/Models/BaseEntity.cs
> +    public class BaseEntity
Мне оставлять id long или на int переделать?

2020-11-10 21:55 UTC, Olya73 commented on ImageBase.WebApp/Repository/Storage/ImageCatalogRepository.cs
> +    public class ImageCatalogRepository : Repository<ImageCatalog>, IImageCatalogRepository
Окей... А как тогда поступить с сервисом (ImageCatalogService)?

2020-11-11 08:14 UTC, fornit1917 commented on ImageBase.WebApp/Data/Models/BaseEntity.cs
> +    public class BaseEntity
```
class BaseEntity<TId>
{
  public TId {get; set;}
}
```

И свои энтити ты наследуешь уже или от BaseEntity<int>, или от BaseEntity<long>. Я сейчас вижу смысл оставить long разве что только для айдишника картинок.

2020-11-11 08:19 UTC, fornit1917 commented on ImageBase.WebApp/Repository/Storage/ImageCatalogRepository.cs
> +    public class ImageCatalogRepository : Repository<ImageCatalog>, IImageCatalogRepository
методы, которые добавляют картинку в папку / убирают картинку из папки / возвращают список картинок в папки с учётом постраничного вывода, можно разместить в CatalogRepository. Ты можешь в CatalogRepository заинжектить контекст EF и работать там с любыми таблицами, не обязательно строго следовать правилу одна таблица - один репозиторий.

2020-11-12 11:28 UTC, fornit1917 requested changes

2020-11-12 11:28 UTC, fornit1917 commented on ImageBase.WebApp/Data/Dtos/PaginationListDto.cs
> +        public static async Task<List<T>> GetItems(IQueryable<T> source, int offset, int limit)
работу с IQueryable лучше убрать отсюда, куда-нибудь в базовы репозиторий. DTO оно на то и DTO, что логики содержать особо никакой не должно, это просто объект для передачи данных.

2020-11-12 11:28 UTC, fornit1917 commented on ImageBase.WebApp/Data/Models/Catalog.cs
> +        public Catalog ParentCatalog { get; set; }
Не исправлено. Я имел в виду сделать такой порядок:

```
Name
ParentCatalogId
UserId

ParentCatalog
User
ImageCatalogs
```

2020-11-12 11:28 UTC, fornit1917 commented on ImageBase.WebApp/Repositories/CatalogRepository.cs
> +        public IQueryable<Image> GetImagesByCatalog(long id)
Хорошей практикой является не возвращать из репозиториев IQueryable без очень веской необходимости. Здесь лучше сразу возвращать PaginationList, и в параметры этот метод пусть принимает limit/offset

2020-11-12 11:28 UTC, fornit1917 commented on ImageBase.WebApp/Services/Implementations/CatalogService.cs
> +            var catalog = _repository.GetImagesByCatalog(id);
лучше придерживаться стандарта, согласно которому мы пишем var только если справа явно понятно, какой тип данных.

```
var i = 123; // ok
var s = "qwe"; // ok
var obj = new SomeObject(); // ok

var something = GetSomething(); // плохо, вместо var лучше написать тип явно
```

2020-11-13 09:16 UTC, merged