#14 rubrics and collections
fornit1917/imagebase pull request #17
Opened 2020-11-14 16:08 UTC by BoDmiSer

I add a new api request for manage with catalog. It doesn't end version

2020-11-16 15:35 UTC, fornit1917 requested changes

2020-11-16 15:35 UTC, fornit1917 commented on ImageBase.WebApp.UnitTests/ControllersTest/CatalogsControllerTests.cs
> +    public class CatalogsControllerTests
Полезность этих тестов довольно низкая. Можно её повысить, настраивая в каждом тесте поведение для мока, и проверять, что контроллер вернул результат, который соотвествует поведению мока. Например, настроить конкретный список возвращаемых каталогов - и проверить, что контроллер вернул именно его.

Вообще на практике на контроллеры редко пишут юнит-тесты, т.к. контроллеры должны быть очень простыми, а вся логика должен быть в сервисах - их и покрываем тестами.

2020-11-16 15:35 UTC, fornit1917 commented on ImageBase.WebApp.UnitTests/ControllersTest/ImagesControllerTest.cs
> +        //public async Task CreateImageActionReturnsResultWithImageDto_OnFailAdd()
Закомментрированный код без особо нужды лучше не оставлять. Если не нужен - значит надо его удалить. Если нужен - раскомментировать.

2020-11-16 15:35 UTC, fornit1917 commented on ImageBase.WebApp/Controllers/CatalogsController.cs
> +    public class CatalogsController : ControllerBase
с какими каталогами работает этот контроллер? С общими или с пользовательскими? Похоже что со всеми подряд.
Напомню, что у нас на UI будет два дерева: для общих папок, доступных для чтения всем пользователям, но доступных для редактирования только админам, и второе дерево для папок личных для текущего пользователя. К ним полный доступ есть у любого пользователя, но только у того, кто является для них владельцем.

Это поведения не было учтено ни здесь, ни в слое сервисов.

2020-11-16 15:35 UTC, fornit1917 commented on ImageBase.WebApp/Controllers/CatalogsController.cs
> +            var allCatalog = await _catalogService.GetCatalogsAsync();
Используем var только если тип явно виден из правой части.
Используем множественное число для имени переменной - allCatalogs.

2020-11-16 15:35 UTC, fornit1917 commented on ImageBase.WebApp/Controllers/ImagesController.cs
> +            return Ok();
фронтенду будет интересно узнать айдишник созданной картинки

2020-11-16 15:35 UTC, fornit1917 commented on ImageBase.WebApp/Services/Implementations/CatalogService.cs
> +            _context.Entry(catalog).State = EntityState.Added;
не очень хорошо такое писать в слое сервисов. В репозитории тогда уж должно быть. И мне непонятно, зачем вообще понадобилось это писать.

2020-11-16 15:35 UTC, fornit1917 commented on ImageBase.WebApp/Startup.cs
> +                    options.UseNpgsql(Configuration.GetConnectionString("MyAspPostgreSQLContext")));
смысл этого изменения?

2020-11-18 13:11 UTC, fornit1917 requested changes

2020-11-18 13:11 UTC, fornit1917 commented on ImageBase.WebApp/Controllers/CatalogsController.cs
> +            bool catalog = await _catalogService.DeleteCatalogAsync(id);
имя переменной не соответствует действительности, должно быть isCatalogDeleted

2020-11-24 13:30 UTC, fornit1917 requested changes

2020-11-24 13:30 UTC, fornit1917 commented on ImageBase.WebApp/Controllers/CatalogsController.cs
> +        public async Task<ActionResult<IEnumerable<CatalogDto>>> GetCatalogsByUser(string userId)
т.е. я могу передать айдишник любого пользователя и получить чужие каталоги?
Я должен получать **свои** и только **свои** каталоги. Ну и общие (для этого у вас отдельный метод)

2020-11-24 13:30 UTC, fornit1917 commented on ImageBase.WebApp/Controllers/CatalogsController.cs
> +        public async Task<ActionResult<IEnumerable<CatalogDto>>> GetSubCatalogsByUserAsync(int parentId, string userId)
аналогично, UserId надо брать из сессии

2020-11-24 13:30 UTC, fornit1917 commented on ImageBase.WebApp/Controllers/CatalogsController.cs
> +        public async Task<ActionResult<CatalogDto>> CreateCatalog(CatalogDto catalog)
а где проверка доступа?

2020-11-24 13:30 UTC, fornit1917 commented on ImageBase.WebApp/Controllers/CatalogsController.cs
> +        public async Task<ActionResult<CatalogDto>> AddImageToCatalog(UpdateImageCatalogDto image)
где проверка доступа? в общие каталоги может добавлять только админ, в пользовательские - только владелец каталога

2020-11-24 13:30 UTC, fornit1917 commented on ImageBase.WebApp/Controllers/CatalogsController.cs
> +        [Authorize(Roles = UserRoles.Admin)]
как обычному пользователю удалить свою личную папку?

2020-11-24 13:30 UTC, fornit1917 commented on ImageBase.WebApp/Controllers/CatalogsController.cs
> +        [Authorize(Roles = UserRoles.Admin)]
Как обычному пользователю удалить картинку из своей собственной папки?

2020-11-24 13:30 UTC, fornit1917 commented on ImageBase.WebApp/Repositories/CatalogRepository.cs
> +            return await _context.Catalogs.Where(c => c.Id == parentId && (c.UserId == userId || c.UserId == null)).AnyAsync();
Похоже тут ошибка в услоавии c.UserId == null

2020-11-24 13:30 UTC, fornit1917 commented on ImageBase.WebApp/Repositories/ImageRepository.cs
> +        public async Task<bool> IsImageTitleAlreadyExists(int id, string title)
нигде не используется, не нужно

2020-11-24 13:52 UTC, Olya73 commented on ImageBase.WebApp/Repositories/CatalogRepository.cs
> +            return await _context.Catalogs.Where(c => c.Id == parentId && (c.UserId == userId || c.UserId == null)).AnyAsync();
Я предполагала, что метод GetSubCatalogsByUserAsync, вызывающий представленный метод, будет вызываться в методе контроллера, как для общих папок так и для пользовательских, т.е. мы возвращаем, либо папки пользователя, либо папки общие, либо ошибку.

2020-11-24 14:09 UTC, Olya73 commented on ImageBase.WebApp/Repositories/CatalogRepository.cs
> +            return await _context.Catalogs.Where(c => c.Id == parentId && (c.UserId == userId || c.UserId == null)).AnyAsync();
Я предполагала, что метод GetSubCatalogsByUserAsync, вызывающий представленный метод, будет вызываться в методах контроллеров, как для общих папок так и для пользовательских, т.е. мы возвращаем, либо папки пользователя, либо папки общие, либо ошибку.

2020-11-28 13:38 UTC, closed without merging