20 hashes indexing by vp tree begin
fornit1917/imagebase pull request #23
Opened 2020-11-24 18:20 UTC by MShemur

2020-11-26 10:54 UTC, fornit1917 requested changes

2020-11-26 10:54 UTC, fornit1917 commented on ImageBase.HashBase.UnitTests/HashBaseUnitTests.cs
> +                new object[]
хорошо бы добавить тест, когда есть объекты с разными айдишниками, но одинаковым хэшем, и убедиться, что они все попадают в результат

2020-11-26 10:54 UTC, fornit1917 commented on ImageBase.HashBase/VPTree.cs
> +        public IEnumerable<HashItem> Data { get; set; }
нигде не используется снаружи. Только при построении. Можно убрать и передавать items как параметр при построении

2020-11-26 10:54 UTC, fornit1917 commented on ImageBase.HashBase/VPTree.cs
> +            List<HashItem> items = Data.ToList();
ToList() создаёт новый список в памяти. У вас рекурсивно этот метод вызывается, каждый раз новый список будет создаваться. Можно подумать как создать список один раз, а потом его переиспользовать, передавать в рекурсивные вызовы его же и индексы границ только например.

2020-11-26 10:54 UTC, fornit1917 commented on ImageBase.HashBase/HashComparer.cs
> +        private readonly HashItem vantagePoint;
вместо HashItem можно тип Long сделать, т.к. нам только хэш отсюда нужен. Тогда не придётся ObjectId=-1 передавать при создании.

2020-11-26 10:54 UTC, fornit1917 commented on ImageBase.HashBase/VPTree.cs
> +        public HashItem VantagePoint { get; set; }
Для тех свойств, которые снаружи не устанавливаются, следует убрать публичный сеттер

2020-11-26 10:54 UTC, fornit1917 commented on ImageBase.HashBase/VPTree.cs
> +        public int Mu { get; set; }
Следует дать более говорящее название

2020-11-26 10:54 UTC, fornit1917 commented on ImageBase.HashBase/VPTreeHashBase.cs
> +        public VPTree Root { get; set; }
почему public?

2020-11-28 09:56 UTC, MShemur commented on ImageBase.HashBase/HashComparer.cs
> +        private readonly HashItem vantagePoint;
в Search нам нужно получить и отсортировать список ID по Hash. не получится отсортировать список HashItem через IComparer<long>. чтоб не создавать c ObjectId=-1 я переделал метод Compare

2020-11-28 09:56 UTC, MShemur commented on ImageBase.HashBase/VPTreeHashBase.cs
> +        public VPTree Root { get; set; }
че б и не))
Поправим

2020-11-28 09:57 UTC, MShemur commented on ImageBase.HashBase/VPTree.cs
> +        public int Mu { get; set; }
Mu-Mu ?)
Поправим)

2020-11-30 09:52 UTC, fornit1917 requested changes

2020-11-30 09:52 UTC, fornit1917 commented on ImageBase.HashBase/HashComparer.cs
> +        private readonly HashItem vantagePoint;
У тебя private переменная HashItem vantagePoint, при этом из неё здесь использается только поле Hash. Значит HashItem vantagePoint можно заменить на long vantagePointHash

2020-11-30 09:52 UTC, fornit1917 commented on ImageBase.HashBase/VPTree.cs
> +            CreteNode();
опечатка в имени метода

2020-11-30 09:52 UTC, fornit1917 commented on ImageBase.HashBase/VPTree.cs
> +            int itemCount = endIndex - startIndex;
нет ли тут ошибки?
endIndex = 1, startIndex=0
endIndex - startIndex = 1, но количество то 2

2020-11-30 09:52 UTC, fornit1917 commented on ImageBase.HashBase/VPTreeHashBase.cs
> +            var allItems = new List<HashItem>();
т.е. вы в этот список помещаете вообще все элементы из radius-окрестности точки hash? И только потом сортируете и берёте первые limit?
Вариант рабочий, но не самый эффективный. Этот список может быть довольно большим. В идеале следует подумать над тем, как организовать структуру данных, чтобы уже в процессе поиска получать элементы в нужном порядке, чтобы можно было взять только первые limit элементов. 

Пока можно не править, но это кандидат на будущую задачу.

2020-11-30 17:35 UTC, MShemur commented on ImageBase.HashBase/VPTree.cs
> +            int itemCount = endIndex - startIndex;
ошибки нет, это количество элементов за исключением опорной точки. я переименовал в childrenCount

2020-11-30 17:37 UTC, MShemur commented on ImageBase.HashBase/VPTreeHashBase.cs
> +            var allItems = new List<HashItem>();
SortedSet ? Как во вступительном задании?

2020-12-01 15:00 UTC, fornit1917 commented on ImageBase.HashBase/VPTreeHashBase.cs
> +            var allItems = new List<HashItem>();
подумаем/обсудим позже

2020-12-01 15:01 UTC, merged