#5 Login, Logout, Cookie, RoleInitializer
fornit1917/imagebase pull request #7
Opened 2020-11-01 19:41 UTC by Olya73

Сделала, как поняла))

2020-11-02 07:34 UTC, fornit1917 commented on ImageBase.WebApp/Controllers/AuthenticationController.cs
> +                return StatusCode(StatusCodes.Status500InternalServerError,
500-я ошибка это когда у тебя база данных упала например) а когда юзер уже существует, это вообще не ошибка, это штатная ситуация, как ошибка валидации

2020-11-02 07:50 UTC, fornit1917 requested changes
Add html views for login and register forms

2020-11-03 08:41 UTC, Olya73 commented
I hope, I did it right. Attributes for models' properties have to be added by Dima.

2020-11-03 10:47 UTC, fornit1917 requested changes

2020-11-03 10:47 UTC, fornit1917 commented on ImageBase.WebApp/Controllers/AuthenticationController.cs
> +                    return RedirectToAction("Index", "Home");
перед этим по идее нужно залогинить юзера через _signInManager, чтоб кука создалась.

2020-11-03 11:12 UTC, merged